repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-xml

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-java
        args: [--autofix]

  - repo: local
    hooks:
      - id: checkstyle
        name: checkstyle
        entry: mvn checkstyle:check
        language: system
        files: \.java$
        pass_filenames: false

  - repo: https://github.com/AliYmn/conventional-commits-check
    rev: V2.0.0
    hooks:
      - id: conventional-commits-check
        stages: [commit-msg]
        args: ['--config', 'commits_check_config.yaml']
